name: T3DP
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.3.1=py37h2c7a002_0
  - pip=21.1.3=py37h06a4308_0
  - python=3.7.10=h12debd9_4
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu102
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - backcall==0.2.0
    - charset-normalizer==2.0.2
    - click==8.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - einops==0.3.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - idna==3.2
    - imageio==2.9.0
    - importlib-metadata==4.6.1
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - networkx==2.5.1
    - opencv-contrib-python==4.5.3.56
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - promise==2.3
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - scikit-image==0.18.2
    - scipy==1.7.0
    - sentry-sdk==1.3.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tifffile==2021.7.2
    - tqdm==4.61.2
    - traitlets==5.0.5
    - urllib3==1.26.6
    - wandb==0.11.0
    - wcwidth==0.2.5
    - yacs==0.1.8
    - zipp==3.5.0
    - joblib==1.1.0
    - pyrender==0.1.45
    - pytest==6.2.5
    - scikit-learn==0.22.2
    - pytube==11.0.1
    - motmetrics==1.2.0


